[package]
name = "ir"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
k-parser.workspace = true
num-bigint = "0.4.6"
serde = {version = "1.0.208", features=["derive"]}
serde_json = "1.0.125"
